-- V1 的 SQLite 业务库：基础档案、当前/历史任职、教育经历、考勤事实分别建表。
-- 不用于 V2 的单张人员宽表，也不用于 Superset/PostgreSQL；由 seed.py 写临时库后校验发布。
PRAGMA foreign_keys = ON;
CREATE TABLE dataset_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE legal_entities (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE locations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, timezone TEXT NOT NULL);
CREATE TABLE departments (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, parent_id INTEGER REFERENCES departments(id), level INTEGER NOT NULL CHECK(level BETWEEN 1 AND 4), division_id INTEGER REFERENCES departments(id));
CREATE TABLE job_families (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE grades (id INTEGER PRIMARY KEY, name TEXT NOT NULL, salary_min INTEGER NOT NULL, salary_max INTEGER NOT NULL CHECK(salary_max>=salary_min));
CREATE TABLE positions (id INTEGER PRIMARY KEY, name TEXT NOT NULL, family_id INTEGER NOT NULL REFERENCES job_families(id), is_manager INTEGER NOT NULL CHECK(is_manager IN (0,1)));
CREATE TABLE schools (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, aliases TEXT NOT NULL, is_985 INTEGER NOT NULL CHECK(is_985 IN (0,1)), is_211 INTEGER NOT NULL CHECK(is_211 IN (0,1)), classification_basis TEXT NOT NULL, source_url TEXT NOT NULL, CHECK(is_985<=is_211));
CREATE TABLE employees (id INTEGER PRIMARY KEY, employee_no TEXT NOT NULL UNIQUE, name TEXT NOT NULL, gender TEXT NOT NULL CHECK(gender IN ('女','男')), birth_date TEXT NOT NULL, hire_date TEXT NOT NULL, termination_date TEXT, employment_type TEXT NOT NULL CHECK(employment_type IN ('正式','实习','外包')), entity_id INTEGER NOT NULL REFERENCES legal_entities(id), location_id INTEGER NOT NULL REFERENCES locations(id), email TEXT NOT NULL UNIQUE, highest_education TEXT NOT NULL DEFAULT '未知' CHECK(highest_education IN ('未知','高中及以下','专科','本科','硕士研究生','博士研究生')), highest_degree TEXT NOT NULL DEFAULT '未知' CHECK(highest_degree IN ('未知','无学位','学士','硕士','博士')), graduation_school_id INTEGER REFERENCES schools(id), major TEXT, graduation_date TEXT, education_mode TEXT NOT NULL DEFAULT '未知' CHECK(education_mode IN ('未知','全日制','非全日制')), CHECK(termination_date IS NULL OR termination_date>=hire_date));
CREATE TABLE employee_education (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), school_id INTEGER NOT NULL REFERENCES schools(id), education_level TEXT NOT NULL, education_rank INTEGER NOT NULL CHECK(education_rank BETWEEN 1 AND 5), degree TEXT NOT NULL CHECK(degree IN ('无学位','学士','硕士','博士')), major TEXT NOT NULL, start_date TEXT NOT NULL, graduation_date TEXT NOT NULL, study_mode TEXT NOT NULL CHECK(study_mode IN ('全日制','非全日制')), CHECK(start_date<graduation_date), UNIQUE(employee_id,education_rank,graduation_date));
CREATE INDEX idx_education_employee_date ON employee_education(employee_id,graduation_date,education_rank);
CREATE INDEX idx_education_school ON employee_education(school_id,employee_id);
-- 私人信息只供模拟完整性演示，query.py 的读取表白名单不开放这张表。
CREATE TABLE employee_private (employee_id INTEGER PRIMARY KEY REFERENCES employees(id), phone TEXT NOT NULL, identity_document TEXT NOT NULL, bank_account TEXT NOT NULL);
CREATE TABLE assignments (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), department_id INTEGER NOT NULL REFERENCES departments(id), manager_id INTEGER REFERENCES employees(id), position_id INTEGER NOT NULL REFERENCES positions(id), grade_id INTEGER NOT NULL REFERENCES grades(id), valid_from TEXT NOT NULL, valid_to TEXT, CHECK(manager_id IS NULL OR manager_id<>employee_id), CHECK(valid_to IS NULL OR valid_to>valid_from), UNIQUE(employee_id,valid_from));
CREATE UNIQUE INDEX uq_current_assignment ON assignments(employee_id) WHERE valid_to IS NULL;
CREATE INDEX idx_assignment_asof ON assignments(employee_id,valid_from,valid_to);
CREATE INDEX idx_assignment_dept ON assignments(department_id,valid_from);
-- 当前管理闭包由 seed.py 预计算；历史业务日期不会切换回历史管理授权。
-- 深度 0/1/大于等于2 分别对应本人/直属/间接下属，security.py 用它限定 V1 候选人员。
CREATE TABLE reporting_closure (ancestor_id INTEGER NOT NULL REFERENCES employees(id), descendant_id INTEGER NOT NULL REFERENCES employees(id), depth INTEGER NOT NULL CHECK(depth>=0), PRIMARY KEY(ancestor_id,descendant_id));
CREATE INDEX idx_closure_desc ON reporting_closure(descendant_id);
CREATE TABLE work_calendar (day TEXT PRIMARY KEY, is_workday INTEGER NOT NULL CHECK(is_workday IN (0,1)), note TEXT NOT NULL);
CREATE TABLE shift_policies (id INTEGER PRIMARY KEY, name TEXT NOT NULL, earliest_in INTEGER NOT NULL, latest_in INTEGER NOT NULL, earliest_out INTEGER NOT NULL, required_work_minutes INTEGER NOT NULL, lunch_minutes INTEGER NOT NULL, version TEXT NOT NULL);
CREATE TABLE attendance_daily (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), day TEXT NOT NULL REFERENCES work_calendar(day), shift_id INTEGER NOT NULL REFERENCES shift_policies(id), status TEXT NOT NULL CHECK(status IN ('正常','远程','请假','缺勤','缺卡')), check_in INTEGER, check_out INTEGER, work_minutes INTEGER NOT NULL CHECK(work_minutes>=0), late_minutes INTEGER NOT NULL CHECK(late_minutes>=0), early_minutes INTEGER NOT NULL CHECK(early_minutes>=0), late_departure_minutes INTEGER NOT NULL CHECK(late_departure_minutes>=0), UNIQUE(employee_id,day), CHECK(check_in IS NULL OR check_out IS NULL OR check_out>=check_in));
CREATE INDEX idx_attendance_day_employee ON attendance_daily(day,employee_id);
CREATE TABLE leave_requests (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), day TEXT NOT NULL, leave_type TEXT NOT NULL, days REAL NOT NULL CHECK(days>0 AND days<=1), approval_status TEXT NOT NULL CHECK(approval_status IN ('已批准','待审批','已拒绝')), approver_id INTEGER REFERENCES employees(id), UNIQUE(employee_id,day));
CREATE TABLE overtime_requests (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), day TEXT NOT NULL, minutes INTEGER NOT NULL CHECK(minutes>0), day_type TEXT NOT NULL DEFAULT '工作日' CHECK(day_type IN ('工作日','周末')), approval_status TEXT NOT NULL CHECK(approval_status IN ('已批准','待审批','已拒绝')), approver_id INTEGER REFERENCES employees(id), UNIQUE(employee_id,day));
CREATE TABLE compensation (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), valid_from TEXT NOT NULL, valid_to TEXT, monthly_base INTEGER NOT NULL CHECK(monthly_base>=0), currency TEXT NOT NULL DEFAULT 'CNY', UNIQUE(employee_id,valid_from));
CREATE TABLE performance_reviews (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), period TEXT NOT NULL, rating TEXT NOT NULL CHECK(rating IN ('卓越','优秀','达标','待提升')), reviewer_id INTEGER REFERENCES employees(id), UNIQUE(employee_id,period));
CREATE TABLE training_courses (id INTEGER PRIMARY KEY, name TEXT NOT NULL, hours REAL NOT NULL);
CREATE TABLE training_enrollments (employee_id INTEGER NOT NULL REFERENCES employees(id), course_id INTEGER NOT NULL REFERENCES training_courses(id), status TEXT NOT NULL, completed_at TEXT, PRIMARY KEY(employee_id,course_id));
CREATE TABLE recruitment_requisitions (id INTEGER PRIMARY KEY, department_id INTEGER NOT NULL REFERENCES departments(id), position_id INTEGER NOT NULL REFERENCES positions(id), openings INTEGER NOT NULL CHECK(openings>0), status TEXT NOT NULL, opened_at TEXT NOT NULL);
CREATE TABLE overtime_attendance (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), day TEXT NOT NULL REFERENCES work_calendar(day), check_in INTEGER NOT NULL, check_out INTEGER NOT NULL, break_minutes INTEGER NOT NULL CHECK(break_minutes>=0), work_minutes INTEGER NOT NULL CHECK(work_minutes>0), CHECK(check_in>=0 AND check_out<=1320 AND check_out>check_in AND work_minutes=check_out-check_in-break_minutes), UNIQUE(employee_id,day));
CREATE INDEX idx_overtime_day_type ON overtime_requests(day_type,day,employee_id);
